# Generated by Django 4.2.3 on 2023-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=40)),
                ('addrr', models.CharField(max_length=40)),
                ('City', models.CharField(max_length=40)),
                ('Phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
